// Photo-stack content. Order: portraits (single-*) first, then landscapes (double-*).
// Captions are PLACEHOLDERS — replace title/location per photo after the section is built.
export type Photo = { src: string; aspect: "portrait" | "landscape"; title: string; location: string };

export const PHOTOS: Photo[] = [
  { src: "/assets/photo-stack/single-1.jpg", aspect: "portrait", title: "Working from Monkey Tribe Hostel", location: "Alleppey, India" },
  { src: "/assets/photo-stack/single-4.jpg", aspect: "portrait", title: "An in-flight view of Mumbai from Indigo Airlines", location: "Mumbai to Goa" },
  { src: "/assets/photo-stack/single-5.jpg", aspect: "portrait", title: "With Queen TuoTuo", location: "Hyderabad, India" },
  { src: "/assets/photo-stack/single-7.jpg", aspect: "portrait", title: "Chowmahalla Palace", location: "Hyderabad, India" },
  { src: "/assets/photo-stack/single-9.jpg", aspect: "portrait", title: "Biryani at Hotel Paradise", location: "Hyderabad, India" },
  { src: "/assets/photo-stack/single-10.jpg", aspect: "portrait", title: "Early morning Shikara ride", location: "Alleppey, India" },
  { src: "/assets/photo-stack/single-11.jpg", aspect: "portrait", title: "Joe Hill from the United Kingdom", location: "Alleppey, India" },
  { src: "/assets/photo-stack/single-12.jpg", aspect: "portrait", title: "Sunset Point", location: "Somewhere near Alleppey, India" },
  { src: "/assets/photo-stack/single-13.jpg", aspect: "portrait", title: "Rui and Paulo from Portugal", location: "Alleppey, India" },
  { src: "/assets/photo-stack/single-14.jpg", aspect: "portrait", title: "Tender Coconut Shake from a local shop", location: "Calicut, India" },
  { src: "/assets/photo-stack/single-16.jpg", aspect: "portrait", title: "Cold brew coffee at SLO Labs", location: "Calicut, India" },
  { src: "/assets/photo-stack/single-17.jpg", aspect: "portrait", title: "SLO Labs", location: "Calicut, India" },
  { src: "/assets/photo-stack/single-19.jpg", aspect: "portrait", title: "Working from Molly's Hostel", location: "Varkala, India" },
  { src: "/assets/photo-stack/single-20.jpg", aspect: "portrait", title: "Philipo from Milano", location: "Varkala, India" },
  { src: "/assets/photo-stack/single-21.jpg", aspect: "portrait", title: "Chicken Pizza at Cafe InDa", location: "Varkala, India" },
  { src: "/assets/photo-stack/single-22.jpg", aspect: "portrait", title: "A beautiful teapot spotted at Nosh Haus", location: "Jew Town, Fort Kochi, India" },
  { src: "/assets/photo-stack/single-24.jpg", aspect: "portrait", title: "Attending demo call from Kaashi Art Cafe", location: "Fort Kochi, India" },
  { src: "/assets/photo-stack/single-25.jpg", aspect: "portrait", title: "Watched Kathakali for the first time", location: "Fort Kochi, India" },
  { src: "/assets/photo-stack/single-26.jpg", aspect: "portrait", title: "Synagogue in Jew Town", location: "Fort Kochi, India" },
  { src: "/assets/photo-stack/single-27.jpg", aspect: "portrait", title: "St. George Syro-Malabar Church", location: "Edapally, India" },
  { src: "/assets/photo-stack/single-29.jpg", aspect: "portrait", title: "Tea with a river view", location: "Ernakulam, India" },
  { src: "/assets/photo-stack/single-30.jpg", aspect: "portrait", title: "I was his first Uber customer", location: "Kochi, India" },
  { src: "/assets/photo-stack/single-31.jpg", aspect: "portrait", title: "Jatayu Earth's Center", location: "Kollam, India" },
  { src: "/assets/photo-stack/single-32.jpg", aspect: "portrait", title: "Cafe Churpi", location: "Varkala, India" },
  { src: "/assets/photo-stack/single-33.jpg", aspect: "portrait", title: "View from Cafe Iyra", location: "Varkala, India" },
  { src: "/assets/photo-stack/single-34.jpg", aspect: "portrait", title: "Me and Founders of Fusepay", location: "Goa, India" },
  { src: "/assets/photo-stack/single-35.jpg", aspect: "portrait", title: "Nool Appam and Lamb Curry", location: "Fort Kochi, India" },
  { src: "/assets/photo-stack/single-36.jpg", aspect: "portrait", title: "Chicken Mandi at Arabian Mandi", location: "Pune, India" },
  { src: "/assets/photo-stack/single-37.jpg", aspect: "portrait", title: "Lemon Tart at Cafe Trouvaille", location: "Fort Kochi, India" },
  { src: "/assets/photo-stack/single-38.jpg", aspect: "portrait", title: "Parotta & Beef curry at Raja Tea Shop", location: "Alleppey, India" },
  { src: "/assets/photo-stack/single-39.jpg", aspect: "portrait", title: "View from Monkey Tribe Hostel", location: "Alleppey, India" },
  { src: "/assets/photo-stack/single-40.jpg", aspect: "portrait", title: "Artist Colleague from Coditas", location: "Pune, India" },
  { src: "/assets/photo-stack/single-41b.jpg", aspect: "portrait", title: "Fractured my wrist within the first hour of offsite", location: "Goa, India" },
  { src: "/assets/photo-stack/single-42b.jpg", aspect: "portrait", title: "Calmly waiting for the Monday Morning Storm", location: "Somewhere near Pune, India" },
  { src: "/assets/photo-stack/double-2.jpg", aspect: "landscape", title: "Colleagues from when I worked at Coditas", location: "Pune, India" },
  { src: "/assets/photo-stack/double-3.jpg", aspect: "landscape", title: "'The Oreo Boys' from Fusepay", location: "Mumbai Airport, India" },
  { src: "/assets/photo-stack/double-15.jpg", aspect: "landscape", title: "Attending Theyyam Performance", location: "Kannur, India" },
  { src: "/assets/photo-stack/double-18.jpg", aspect: "landscape", title: "Beach view from the South side", location: "Varkala, India" },
  { src: "/assets/photo-stack/double-23.jpg", aspect: "landscape", title: "Travelled in Water Metro", location: "Fort Kochi, India" },
  { src: "/assets/photo-stack/double-28.jpg", aspect: "landscape", title: "Met some brightest minds in Neuro-fields\nFrom Japan, Korea, and Bengaluru", location: "Alleppey, India" },
];
